spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 156761
    url: jdbc:mysql://localhost:3306/ssm
  application:
    name: springboot_demo01
  redis:
    host: 192.168.154.100
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 10

server:
  port: 8888

mybatis-plus:
  type-aliases-package: com.example.springboot_demo01.pojo
  configuration:
    map-underscore-to-camel-case: true

